data:
    dataset: "IMAGENET512"
    image_size: 512
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32
    num_classes: 1000

model:
    model_type: "guided_diffusion"
    is_upsampling: false
    image_size: 512
    in_channels: 3
    model_channels: 256
    out_channels: 6
    num_res_blocks: 2
    attention_resolutions: [16, 32, 64] # [512 // 32, 512 // 16, 512 // 8]
    dropout: 0.0
    channel_mult: [0.5, 1, 1, 2, 2, 4, 4]
    conv_resample: true
    dims: 2
    num_classes: 1000
    use_checkpoint: false
    use_fp16: false
    num_heads: 4
    num_head_channels: 64
    num_heads_upsample: -1
    use_scale_shift_norm: true
    resblock_updown: true
    use_new_attention_order: false
    var_type: fixedlarge
    ema: false
    ckpt_dir: "~/ddpm_ckpt/imagenet512/512x512_diffusion.pt"

classifier:
    ckpt_dir: "~/ddpm_ckpt/imagenet512/512x512_classifier.pt"
    image_size: 512
    in_channels: 3
    model_channels: 128
    out_channels: 1000
    num_res_blocks: 2
    attention_resolutions: [16, 32, 64] # [256 // 32, 256 // 16, 256 // 8]
    channel_mult: [0.5, 1, 1, 2, 2, 4, 4]
    use_fp16: false
    num_head_channels: 64
    use_scale_shift_norm: true
    resblock_updown: true
    pool: "attention"

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    total_N: 1000
    schedule: "linear"
    batch_size: 20
    last_only: True
    fid_stats_dir: "fid_stats/VIRTUAL_imagenet512.npz"
    fid_total_samples: 50000
    fid_batch_size: 200
    cond_class: true
    classifier_scale: 4.0
